"""
run_mock_pipeline.py
--------------------
Full mock training pipeline for the Email Priority Classification System.

This script:
1. Loads the preprocessed email dataset (generated by generate_dataset.py)
2. Engineers features (TF-IDF + metadata + urgency signals)
3. Trains three classifiers: Logistic Regression, Random Forest, XGBoost
4. Evaluates all models on a held-out test set
5. Saves trained models to models/
6. Generates full evidence artefacts to evidence/:
       confusion_matrix_<model>.png
       roc_curve_<model>.png
       model_comparison.png
       training_results.json
       evaluation_report.json
       classification_reports.txt
       training_log.txt

Usage:
    python run_mock_pipeline.py
"""
from __future__ import annotations

import sys
import json
import time
import pickle
import logging
import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")          # non-interactive backend
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import (
    accuracy_score, f1_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
    roc_curve, auc,
)
from sklearn.preprocessing import label_binarize
from imblearn.over_sampling import SMOTE
from scipy.sparse import issparse
import xgboost as xgb

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR       = Path(__file__).resolve().parent
PROCESSED_CSV  = BASE_DIR / "data" / "processed" / "processed_emails.csv"
MODELS_DIR     = BASE_DIR / "models"
EVIDENCE_DIR   = BASE_DIR.parent.parent / "evidence"   # project-level evidence/
MODELS_DIR.mkdir(parents=True, exist_ok=True)
EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)

LABEL_NAMES    = ["critical", "high", "normal", "low"]
RANDOM_STATE   = 42
CV_FOLDS       = 5
TFIDF_FEATURES = 5000

# ── Logging ───────────────────────────────────────────────────────────────────
LOG_PATH = EVIDENCE_DIR / "training_log.txt"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_PATH, mode="w"),
    ],
)
log = logging.getLogger(__name__)


# ── Feature engineering ───────────────────────────────────────────────────────

CRITICAL_KW = [
    "urgent", "asap", "immediately", "critical", "action required",
    "time sensitive", "emergency", "deadline today", "respond now",
    "right away", "top priority", "high priority", "must read",
    "time-sensitive", "urgent action", "immediate attention",
]
HIGH_KW = [
    "important", "please respond", "follow up", "by eod", "by end of day",
    "by friday", "meeting", "deadline", "required", "mandatory",
    "please review", "response needed", "action needed", "please confirm",
    "awaiting your response", "please advise", "kindly respond",
    "by tomorrow", "by monday", "request for", "follow-up",
]
LOW_KW = [
    "fyi", "newsletter", "unsubscribe", "no reply", "automated",
    "noreply", "notification", "digest", "weekly", "monthly",
    "no-reply", "do not reply", "you are receiving this", "mailing list",
    "this is an automated", "subscription", "promotional", "advertisement",
]
ALL_URGENCY_KW = CRITICAL_KW + HIGH_KW


def _extract_meta(df: pd.DataFrame) -> np.ndarray:
    import re
    feats = pd.DataFrame(index=df.index)
    feats["recipient_count"] = df.get("recipient_count", 0).fillna(0)
    feats["has_cc"]          = df.get("has_cc", 0).fillna(0)
    feats["has_bcc"]         = df.get("has_bcc", 0).fillna(0)
    feats["hour_of_day"]     = pd.to_numeric(df.get("hour_of_day", -1), errors="coerce").fillna(-1)
    feats["day_of_week"]     = pd.to_numeric(df.get("day_of_week", -1), errors="coerce").fillna(-1)
    feats["is_weekend"]      = feats["day_of_week"].apply(lambda d: int(d in (5, 6)) if d >= 0 else 0)
    feats["subject_length"]  = df["subject"].str.len().fillna(0)
    feats["body_length"]     = df["body"].str.len().fillna(0)
    feats["word_count"]      = df["body"].str.split().str.len().fillna(0)
    feats["is_reply"]        = df["subject"].str.lower().str.startswith("re:").astype(int)
    feats["is_forward"]      = (
        df["subject"].str.lower().str.startswith("fw:")
        | df["subject"].str.lower().str.startswith("fwd:")
    ).astype(int)

    texts = (df["subject"].fillna("") + " " + df["body"].fillna("").str[:500]).str.lower()
    feats["urgency_kw_count"] = texts.apply(
        lambda t: sum(1 for kw in ALL_URGENCY_KW if kw in t)
    )
    feats["has_deadline"] = texts.str.contains(
        r"\b(deadline|due date|by \w+day|by eod)\b", regex=True
    ).astype(int)
    feats["has_question"]      = df["body"].apply(lambda b: int("?" in str(b)))
    feats["exclamation_count"] = df["body"].apply(lambda b: str(b).count("!"))

    # Sender domain hash
    def _dhash(s):
        import re
        m = re.search(r"@([\w.\-]+)", str(s))
        return (hash(m.group(1).lower()) % (2**15)) if m else 0
    feats["sender_domain_hash"] = df["sender"].apply(_dhash)

    return feats.astype(float).values


def build_features(df: pd.DataFrame):
    texts = (df["subject"].fillna("") + " " + df["body"].fillna("")).tolist()
    tfidf = TfidfVectorizer(
        max_features=TFIDF_FEATURES,
        ngram_range=(1, 2),
        sublinear_tf=True,
        min_df=2,
        max_df=0.95,
    )
    X_tfidf = tfidf.fit_transform(texts)
    X_meta  = _extract_meta(df)
    X_combined = np.hstack([X_tfidf.toarray(), X_meta]).astype(np.float32)
    y = df["priority"].values.astype(int)
    log.info("Feature matrix: %s  |  classes: %s", X_combined.shape, np.bincount(y).tolist())
    return X_combined, y, tfidf


def _apply_smote(X, y):
    counts  = np.bincount(y)
    k       = min(5, counts.min() - 1)
    if k < 1:
        return X, y
    try:
        sm = SMOTE(random_state=RANDOM_STATE, k_neighbors=k)
        X_r, y_r = sm.fit_resample(X, y)
        log.info("SMOTE: %d → %d samples", len(y), len(y_r))
        return X_r, y_r
    except Exception as exc:
        log.warning("SMOTE skipped (%s)", exc)
        return X, y


def _cv(model, X, y):
    skf = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
    res = cross_validate(model, X, y, cv=skf,
                         scoring=["accuracy", "f1_macro"],
                         n_jobs=-1)
    return {
        "cv_accuracy_mean": float(np.mean(res["test_accuracy"])),
        "cv_accuracy_std":  float(np.std(res["test_accuracy"])),
        "cv_f1_macro_mean": float(np.mean(res["test_f1_macro"])),
        "cv_f1_macro_std":  float(np.std(res["test_f1_macro"])),
    }


# ── Training functions ────────────────────────────────────────────────────────

def train_logistic_regression(X_train, y_train, X_test, y_test, X_all, y_all):
    log.info("=== Training Logistic Regression (TF-IDF only, no SMOTE) ===")
    # Use TF-IDF features only (first TFIDF_FEATURES cols) — fastest for LR
    n_tfidf = TFIDF_FEATURES
    X_tr_tfidf = X_train[:, :n_tfidf]
    X_te_tfidf = X_test[:, :n_tfidf]
    X_all_tfidf = X_all[:, :n_tfidf]
    model = LogisticRegression(
        max_iter=2000, C=5.0, solver="lbfgs",
        random_state=RANDOM_STATE, n_jobs=-1
    )
    t0 = time.time()
    model.fit(X_tr_tfidf, y_train)
    elapsed = time.time() - t0
    y_pred  = model.predict(X_te_tfidf)
    acc     = accuracy_score(y_test, y_pred)
    f1      = f1_score(y_test, y_pred, average="macro", zero_division=0)
    log.info("LR  accuracy=%.4f  macro_f1=%.4f  time=%.1fs", acc, f1, elapsed)
    cv = _cv(model, X_all_tfidf, y_all)
    log.info("LR  CV accuracy=%.4f±%.4f", cv["cv_accuracy_mean"], cv["cv_accuracy_std"])
    joblib.dump(model, MODELS_DIR / "logistic_regression.pkl")
    return model, y_pred, {"model": "logistic_regression", "accuracy": acc,
                            "macro_f1": f1, "train_time_s": round(elapsed, 2), **cv}


def train_random_forest(X_train, y_train, X_test, y_test, X_all, y_all):
    log.info("=== Training Random Forest ===")
    X_tr, y_tr = _apply_smote(X_train, y_train)
    model = RandomForestClassifier(
        n_estimators=200, max_depth=30,
        min_samples_split=5, min_samples_leaf=2,
        n_jobs=-1, random_state=RANDOM_STATE, class_weight="balanced"
    )
    t0 = time.time()
    model.fit(X_tr, y_tr)
    elapsed = time.time() - t0
    y_pred  = model.predict(X_test)
    acc     = accuracy_score(y_test, y_pred)
    f1      = f1_score(y_test, y_pred, average="macro", zero_division=0)
    log.info("RF  accuracy=%.4f  macro_f1=%.4f  time=%.1fs", acc, f1, elapsed)
    cv = _cv(model, X_all, y_all)
    joblib.dump(model, MODELS_DIR / "random_forest.pkl")
    return model, y_pred, {"model": "random_forest", "accuracy": acc,
                            "macro_f1": f1, "train_time_s": round(elapsed, 2), **cv}


def train_xgboost(X_train, y_train, X_test, y_test, X_all, y_all):
    log.info("=== Training XGBoost ===")
    X_tr, y_tr = _apply_smote(X_train, y_train)
    model = xgb.XGBClassifier(
        n_estimators=300, max_depth=6, learning_rate=0.1,
        subsample=0.8, colsample_bytree=0.8,
        eval_metric="mlogloss", random_state=RANDOM_STATE,
        n_jobs=-1, tree_method="hist", verbosity=0
    )
    t0 = time.time()
    model.fit(X_tr, y_tr, eval_set=[(X_test, y_test)], verbose=False)
    elapsed = time.time() - t0
    y_pred  = model.predict(X_test)
    acc     = accuracy_score(y_test, y_pred)
    f1      = f1_score(y_test, y_pred, average="macro", zero_division=0)
    log.info("XGB accuracy=%.4f  macro_f1=%.4f  time=%.1fs", acc, f1, elapsed)
    cv = _cv(model, X_all, y_all)
    joblib.dump(model, MODELS_DIR / "xgboost_model.pkl")
    return model, y_pred, {"model": "xgboost", "accuracy": acc,
                            "macro_f1": f1, "train_time_s": round(elapsed, 2), **cv}


# ── Evidence generation ───────────────────────────────────────────────────────

def _full_metrics(y_true, y_pred) -> dict:
    acc    = float(accuracy_score(y_true, y_pred))
    macro_f1 = float(f1_score(y_true, y_pred, average="macro", zero_division=0))
    prec, rec, f1c, sup = precision_recall_fscore_support(
        y_true, y_pred, labels=list(range(4)), zero_division=0)
    cm   = confusion_matrix(y_true, y_pred, labels=list(range(4))).tolist()
    rep  = classification_report(
        y_true, y_pred, target_names=LABEL_NAMES, output_dict=True, zero_division=0)
    per_class = {
        LABEL_NAMES[i]: {
            "precision": float(prec[i]), "recall": float(rec[i]),
            "f1": float(f1c[i]), "support": int(sup[i])
        } for i in range(4)
    }
    return {"accuracy": acc, "macro_f1": macro_f1, "per_class": per_class,
            "confusion_matrix": cm, "classification_report": rep}


def plot_confusion_matrix(cm_data, model_name: str, accuracy: float):
    cm = np.array(cm_data)
    fig, ax = plt.subplots(figsize=(7, 6))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=LABEL_NAMES, yticklabels=LABEL_NAMES,
        linewidths=0.5, linecolor="gray", ax=ax,
        annot_kws={"size": 13},
    )
    ax.set_xlabel("Predicted Label", fontsize=12)
    ax.set_ylabel("True Label", fontsize=12)
    ax.set_title(
        f"{model_name.replace('_', ' ').title()}\nConfusion Matrix  (accuracy = {accuracy:.2%})",
        fontsize=13, fontweight="bold"
    )
    plt.tight_layout()
    path = EVIDENCE_DIR / f"confusion_matrix_{model_name}.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log.info("Saved confusion matrix: %s", path)


def plot_model_comparison(results: list[dict]):
    names = [r["model"].replace("_", " ").title() for r in results]
    accs  = [r["accuracy"] for r in results]
    f1s   = [r["macro_f1"] for r in results]

    x = np.arange(len(names))
    w = 0.35
    fig, ax = plt.subplots(figsize=(9, 5))
    bars1 = ax.bar(x - w/2, accs, w, label="Accuracy",  color="#4C72B0", alpha=0.85)
    bars2 = ax.bar(x + w/2, f1s,  w, label="Macro F1",  color="#DD8452", alpha=0.85)
    ax.set_ylim(0, 1.05)
    ax.set_xticks(x)
    ax.set_xticklabels(names, fontsize=11)
    ax.set_ylabel("Score", fontsize=12)
    ax.set_title("Model Comparison: Accuracy vs Macro F1", fontsize=13, fontweight="bold")
    ax.axhline(0.90, color="red", linestyle="--", linewidth=1.2, label="90% threshold")
    ax.legend(fontsize=10)
    for bar in bars1:
        ax.annotate(f"{bar.get_height():.3f}",
                    xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                    xytext=(0, 4), textcoords="offset points", ha="center", fontsize=9)
    for bar in bars2:
        ax.annotate(f"{bar.get_height():.3f}",
                    xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                    xytext=(0, 4), textcoords="offset points", ha="center", fontsize=9)
    plt.tight_layout()
    path = EVIDENCE_DIR / "model_comparison.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log.info("Saved model comparison: %s", path)


def plot_roc_curves(models_data: list[dict], X_test, y_test):
    """Plot one-vs-rest ROC curves for all models."""
    y_bin = label_binarize(y_test, classes=[0, 1, 2, 3])
    fig, axes = plt.subplots(1, len(models_data), figsize=(6 * len(models_data), 5))
    if len(models_data) == 1:
        axes = [axes]

    for ax, item in zip(axes, models_data):
        model     = item["model_obj"]
        name      = item["name"]
        X_input   = item.get("X_test_input", X_test)
        if hasattr(model, "predict_proba"):
            y_score = model.predict_proba(X_input)
        else:
            continue
        for cls_i, cls_name in enumerate(LABEL_NAMES):
            fpr, tpr, _ = roc_curve(y_bin[:, cls_i], y_score[:, cls_i])
            roc_auc = auc(fpr, tpr)
            ax.plot(fpr, tpr, lw=1.5, label=f"{cls_name} (AUC={roc_auc:.2f})")
        ax.plot([0,1],[0,1],"k--", lw=0.8)
        ax.set_xlim(0, 1); ax.set_ylim(0, 1.02)
        ax.set_xlabel("False Positive Rate", fontsize=10)
        ax.set_ylabel("True Positive Rate", fontsize=10)
        ax.set_title(f"ROC — {name.replace('_',' ').title()}", fontsize=11, fontweight="bold")
        ax.legend(fontsize=8, loc="lower right")

    plt.tight_layout()
    path = EVIDENCE_DIR / "roc_curves.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log.info("Saved ROC curves: %s", path)


def plot_class_distribution(df: pd.DataFrame):
    counts = df["priority_label"].value_counts()[LABEL_NAMES]
    colors = ["#e74c3c", "#e67e22", "#3498db", "#95a5a6"]
    fig, ax = plt.subplots(figsize=(7, 4))
    bars = ax.bar(LABEL_NAMES, counts.values, color=colors, alpha=0.85, edgecolor="white")
    ax.set_xlabel("Priority Class", fontsize=12)
    ax.set_ylabel("Number of Emails", fontsize=12)
    ax.set_title("Dataset Class Distribution", fontsize=13, fontweight="bold")
    for bar, cnt in zip(bars, counts.values):
        pct = cnt / len(df) * 100
        ax.annotate(f"{cnt}\n({pct:.1f}%)",
                    xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                    xytext=(0, 5), textcoords="offset points", ha="center", fontsize=10)
    plt.tight_layout()
    path = EVIDENCE_DIR / "class_distribution.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log.info("Saved class distribution: %s", path)


def plot_feature_importance(model, model_name: str, feature_names: list, top_n: int = 20):
    """Plot top-N feature importances for tree-based models."""
    if not hasattr(model, "feature_importances_"):
        return
    importances = model.feature_importances_
    indices     = np.argsort(importances)[::-1][:top_n]
    top_names   = [feature_names[i] if i < len(feature_names) else f"f{i}"
                   for i in indices]
    top_vals    = importances[indices]

    fig, ax = plt.subplots(figsize=(8, 6))
    colors = plt.cm.viridis(np.linspace(0.3, 0.9, top_n))
    ax.barh(top_names[::-1], top_vals[::-1], color=colors)
    ax.set_xlabel("Feature Importance", fontsize=11)
    ax.set_title(f"Top {top_n} Features — {model_name.replace('_',' ').title()}",
                 fontsize=12, fontweight="bold")
    plt.tight_layout()
    path = EVIDENCE_DIR / f"feature_importance_{model_name}.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log.info("Saved feature importance: %s", path)


def save_classification_reports(results_metrics: dict):
    """Write human-readable classification reports to a text file."""
    path = EVIDENCE_DIR / "classification_reports.txt"
    sep  = "=" * 70 + "\n"
    with open(path, "w") as fh:
        fh.write("EMAIL PRIORITY CLASSIFICATION — MODEL EVALUATION REPORT\n")
        fh.write(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        fh.write(sep)
        for name, m in results_metrics.items():
            fh.write(f"\nModel: {name.replace('_',' ').upper()}\n")
            fh.write(f"  Accuracy:  {m['accuracy']:.4f}\n")
            fh.write(f"  Macro F1:  {m['macro_f1']:.4f}\n")
            fh.write("\n  Per-class metrics:\n")
            for cls, vals in m["per_class"].items():
                fh.write(f"    {cls:<10}  precision={vals['precision']:.3f}  "
                         f"recall={vals['recall']:.3f}  f1={vals['f1']:.3f}  "
                         f"support={vals['support']}\n")
            fh.write("\n  Confusion Matrix (rows=true, cols=pred):\n")
            cm = m["confusion_matrix"]
            header = "            " + "  ".join(f"{l:>10}" for l in LABEL_NAMES) + "\n"
            fh.write(header)
            for i, row in enumerate(cm):
                row_str = "  ".join(f"{v:>10}" for v in row)
                fh.write(f"  {LABEL_NAMES[i]:<10}  {row_str}\n")
            fh.write("\n" + sep)
    log.info("Saved classification reports: %s", path)


# ── Main pipeline ─────────────────────────────────────────────────────────────

def main():
    log.info("=" * 60)
    log.info("  Email Priority Classification — Mock Training Pipeline")
    log.info("  Started: %s", datetime.datetime.now().isoformat())
    log.info("=" * 60)

    # 1. Load dataset
    if not PROCESSED_CSV.exists():
        log.error("Dataset not found. Run generate_dataset.py first.")
        sys.exit(1)

    df = pd.read_csv(PROCESSED_CSV)
    log.info("Loaded %d emails from %s", len(df), PROCESSED_CSV)

    # Plot class distribution
    plot_class_distribution(df)

    # 2. Feature engineering
    log.info("--- Feature Engineering ---")
    X, y, tfidf_vectorizer = build_features(df)
    feature_names = (tfidf_vectorizer.get_feature_names_out().tolist()
                     + [f"meta_{i}" for i in range(X.shape[1] - TFIDF_FEATURES)])

    # Save vectorizer
    joblib.dump(tfidf_vectorizer, MODELS_DIR / "tfidf_vectorizer.pkl")
    log.info("TF-IDF vectorizer saved.")

    # 3. Train / test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
    )
    log.info("Train: %d  |  Test: %d", len(y_train), len(y_test))

    # 4. Train models
    log.info("--- Model Training ---")
    lr_model,  lr_pred,  lr_info  = train_logistic_regression(X_train, y_train, X_test, y_test, X, y)
    rf_model,  rf_pred,  rf_info  = train_random_forest(X_train, y_train, X_test, y_test, X, y)
    xgb_model, xgb_pred, xgb_info = train_xgboost(X_train, y_train, X_test, y_test, X, y)

    all_train_results = [lr_info, rf_info, xgb_info]

    # 5. Evaluation metrics
    log.info("--- Evaluating Models ---")
    eval_metrics = {}
    model_objects = []
    for model, y_pred, info in [
        (lr_model,  lr_pred,  lr_info),
        (rf_model,  rf_pred,  rf_info),
        (xgb_model, xgb_pred, xgb_info),
    ]:
        name = info["model"]
        m    = _full_metrics(y_test, y_pred)
        m.update({k: v for k, v in info.items() if k not in ("model",)})
        eval_metrics[name] = m
        x_input = X_test[:, :TFIDF_FEATURES] if name == "logistic_regression" else X_test
        model_objects.append({"model_obj": model, "name": name, "X_test_input": x_input})
        log.info("%-25s  accuracy=%.4f  macro_f1=%.4f", name, m["accuracy"], m["macro_f1"])

    # 6. Determine best model
    best_name = max(eval_metrics, key=lambda k: eval_metrics[k]["macro_f1"])
    best_acc  = eval_metrics[best_name]["accuracy"]
    best_f1   = eval_metrics[best_name]["macro_f1"]
    log.info("Best model: %s  (accuracy=%.4f  macro_f1=%.4f)", best_name, best_acc, best_f1)
    (MODELS_DIR / "best_model.txt").write_text(best_name)

    # 7. Save JSON artefacts
    training_results = {
        "training_date":  datetime.datetime.now().isoformat(),
        "n_samples":      int(len(df)),
        "n_train":        int(len(y_train)),
        "n_test":         int(len(y_test)),
        "n_features":     int(X.shape[1]),
        "random_state":   RANDOM_STATE,
        "cv_folds":       CV_FOLDS,
        "models": {r["model"]: r for r in all_train_results},
    }
    eval_report = {
        "evaluation_date": datetime.datetime.now().isoformat(),
        "best_model":      best_name,
        "needs_fallback":  best_acc < 0.75,
        "thresholds":      {"accuracy": 0.75, "macro_f1": 0.65},
        "models":          eval_metrics,
    }

    with open(MODELS_DIR / "training_results.json", "w") as fh:
        json.dump(training_results, fh, indent=2, default=str)
    with open(MODELS_DIR / "evaluation_report.json", "w") as fh:
        json.dump(eval_report, fh, indent=2, default=str)

    # Copy JSONs to evidence dir too
    with open(EVIDENCE_DIR / "training_results.json", "w") as fh:
        json.dump(training_results, fh, indent=2, default=str)
    with open(EVIDENCE_DIR / "evaluation_report.json", "w") as fh:
        json.dump(eval_report, fh, indent=2, default=str)

    log.info("JSON artefacts saved.")

    # 8. Generate evidence plots
    log.info("--- Generating Evidence Plots ---")
    for name, m in eval_metrics.items():
        plot_confusion_matrix(m["confusion_matrix"], name, m["accuracy"])

    plot_model_comparison([
        {"model": n, "accuracy": eval_metrics[n]["accuracy"],
         "macro_f1": eval_metrics[n]["macro_f1"]}
        for n in eval_metrics
    ])
    plot_roc_curves(model_objects, X_test, y_test)
    plot_feature_importance(rf_model,  "random_forest", feature_names)
    plot_feature_importance(xgb_model, "xgboost",       feature_names)
    save_classification_reports(eval_metrics)

    # 9. Summary
    log.info("=" * 60)
    log.info("  Pipeline Complete: %s", datetime.datetime.now().isoformat())
    log.info("  Best model: %-20s  accuracy=%.4f  macro_f1=%.4f",
             best_name, best_acc, best_f1)
    log.info("  Evidence saved to: %s", EVIDENCE_DIR)
    log.info("=" * 60)

    print("\n" + "=" * 60)
    print("TRAINING SUMMARY")
    print("=" * 60)
    for name, m in eval_metrics.items():
        marker = " ← BEST" if name == best_name else ""
        print(f"  {name:<25}  accuracy={m['accuracy']:.4f}  macro_f1={m['macro_f1']:.4f}{marker}")
    print(f"\n  Evidence folder: {EVIDENCE_DIR}")
    print("=" * 60)


if __name__ == "__main__":
    main()
