source "https://rubygems.org"
ruby "3.3.4"

gem "rails", "~> 7.2.0"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# HTTP client for calling the Python Flask ML API
gem "httparty"

# Charts
gem "chartkick"
gem "groupdate"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
